/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_common.h"
#include "fsl_gpio.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitPeripherals functional group */
/* Alias for GPIO5 peripheral */
#define GPIO5_GPIO GPIO5
/* Alias for PORT5 */
#define GPIO5_PORT PORT5
/* GPIO5 interrupt vector ID (number). */
#define GPIO5_INT_0_IRQN GPIO50_IRQn
/* GPIO5 interrupt vector priority. */
#define GPIO5_INT_0_IRQ_PRIORITY 2
/* GPIO5 interrupt handler identifier. */
#define GPIO5_INT_0_IRQHANDLER GPIO50_IRQHandler

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/

void BOARD_InitPeripherals(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
